### ISSUE TITLE
Alpine image might not connect to private DB URL

### ISSUE THREAD

**Issue by rgmvisser** [railwayapp-templates/postgres-s3-backups#15]
The script wasn't working and found that the alpine docker image might work nicely with the private DB URLs: https://docs.railway.app/guides/private-networking#workaround-for-alpine-based-images

I switched it to a node base slim image, but it looks like it is using a lot more memory now. So maybe easier to use the workaround?

My PR:

```
FROM node:18-bullseye-slim as build

ENV NPM_CONFIG_UPDATE_NOTIFIER=false
ENV NPM_CONFIG_FUND=false

WORKDIR /root

COPY package*.json tsconfig.json ./
COPY src ./src

RUN npm install && \
    npm run build && \
    npm prune --production

FROM build as app

WORKDIR /root

COPY --from=build /root/node_modules ./node_modules
COPY --from=build /root/dist ./dist

ARG PG_VERSION='15'

RUN apt-get update && apt-get install -y wget gnupg2 lsb-release
RUN echo "deb http://apt.postgresql.org/pub/repos/apt/ $(lsb_release -cs)-pgdg main" | tee /etc/apt/sources.list.d/pgdg.list && \
    wget --quiet -O - https://www.postgresql.org/media/keys/ACCC4CF8.asc | apt-key add -
RUN apt-get update && apt-get install -y postgresql-client-${PG_VERSION}

CMD sleep 3 && \
    node dist/index.js
```

Happy to make a PR if this makes sense @brody192

**Comment by brody192** [comment]
Thanks for opening this issue, but I'm okay with keeping the alpine image for a few reasons.
- smaller image
- slightly simpler dockerfile
- the template does come with the alpine work around variable added
but most importantly
- the alpine work around variable will not be needed for much longer

**Comment by rgmvisser** [comment]
> the alpine work around variable will not be needed for much longer

Do you have an idea of when this won't be needed anymore? Without it, it doesn't work for me atm

**Comment by rgmvisser** [comment]
Ahhh I just saw that the template got updated with the env variable. I should have noticed that as it would have saved me an hour or two :P

**Comment by brody192** [comment]
FWIW, With the V2 runtime that is now in public beta there is no need for an alpine workaround variable.
