### ISSUE TITLE
While the server is inactive/not running, it stops making backups

### ISSUE THREAD

**Issue by gadatos** [railwayapp-templates/postgres-s3-backups#30]
There were server issues in the EU region on October 3rd. Since then, the automated system has been idle and hasn't been making backups. I only noticed this during the next outage which occurred on October 23rd, also in the EU West region

**Comment by brody192** [comment]
Hello,

That doesn't sound like an issue with the template itself, sounds like something you may have misconfigured.

In that case, please open a post on our help station - https://help.railway.app/
