### ISSUE TITLE
Allow customisation of backup prefix

### ISSUE THREAD

**Issue by njoguamos** [railwayapp-templates/postgres-s3-backups#4]
At the moment, the backup is taking this example format
```bash
backup-2022-09-28T14:00:00.059Z.tar.gz
```

It would be nice if we are able to set the backup prefix i.e
```bash
my-app-2022-09-28T14:00:00.059Z.tar.gz
```

This is can be useful when backing up multiple databases on the same bucket.

I can work on a PR for this.

**Comment by FarazPatankar** [comment]
Hey, thanks for fixing #2. Regarding this issue, what you're suggesting does make sense. How were you thinking about implementing it?

**Comment by njoguamos** [comment]
I had a situation where I was backing up multiple applications in a single bucket.

[I solved it by adding a variable to specify the backup folder](https://github.com/railwayapp-templates/postgres-s3-backups/commit/13cd9dafcdbcc11414100a144afa5bca25da63f3)
