### ISSUE TITLE
How can I restore the backup ?

### ISSUE THREAD

**Issue by sostenesapollo** [railwayapp-templates/postgres-s3-backups#8]
I'm struggling to restore, as this backup creates a lot of .dat files and I'm not able to set the files in docker

**Comment by amserra** [comment]
Hey @mike-choi-solsim . I tried the command you suggested, but I get the following error:
`pg_restore: error: one of -d/--dbname and -f/--file must be specified`

I then specified a newly created database with the `-d` flag, like so:
`pg_restore -d mynewdbname -v backup.tar.gz`

But I get the following error:
`pg_restore: error: input file does not appear to be a valid archive`.

Any idea?

**Comment by brody192** [comment]
Yep, [drmarshall](https://github.com/drmarshall) is correct, you will need to unzip the gzip archive first, but not the .tar archive.

Or you could pipe it through gzip to pg_restore.
